'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3649
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GestioneProduzione.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property accessories_text_editor_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accessories_text_editor_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property accessories_text_editor_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accessories_text_editor_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property apply() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apply", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property book_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property book_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cerca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cerca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property db_comit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("db_comit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dialog_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog_close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_new_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_new_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_new_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_new_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document_print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property editcopy_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editcopy_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exec() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exec", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property export_excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export_excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property export_pdf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export_pdf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property export_word() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export_word", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property format_list_ordered_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("format_list_ordered_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property format_list_ordered_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("format_list_ordered_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property format_list_ordered_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("format_list_ordered_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property games_difficult() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("games_difficult", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help_about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kjobviewer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kjobviewer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kodo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kodo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kuser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kuser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledorange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledorange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledorange1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledorange1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledpurple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledpurple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledpurple1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledpurple1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledyellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledyellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledyellow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledyellow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property list_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property list_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property list_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property list_add_font() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list_add_font", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mime_lyx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mime_lyx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pdf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Printers2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Printers2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property product_finished_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("product_finished_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property product_finished_config_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("product_finished_config_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property product_finished_level_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("product_finished_level_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_all() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_all", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property view_list_details_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_list_details_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property view_list_details_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_list_details_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property view_list_details_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_list_details_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property word() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("word", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
